name: NMSUnlocked
main: com.zainlessbrombie.mc.nmsunlockedd.Main
version: ${pluginVersion}
authors: [ZainlessBrombie]
load: STARTUP
commands:
   nmsunlocked:
      description: View plugin information such as version and how many and which classes have been Reassembled
      usage: '"/nmsunlocked"  and  "/nmsunlocked list"'
permissions:
  nmsunlocked.status:
    description: Enables full viewing of the plugin status. Anybody who does not have this permission will only see a reduced version.
    default: op
